// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: XMsgHead.proto
// Protobuf C++ Version: 5.28.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_XMsgHead_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_XMsgHead_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5028003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_XMsgHead_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_XMsgHead_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_XMsgHead_2eproto;
namespace XMsg {
class XMsgHead;
struct XMsgHeadDefaultTypeInternal;
extern XMsgHeadDefaultTypeInternal _XMsgHead_default_instance_;
}  // namespace XMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace XMsg {

// ===================================================================


// -------------------------------------------------------------------

class XMsgHead final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:XMsg.XMsgHead) */ {
 public:
  inline XMsgHead() : XMsgHead(nullptr) {}
  ~XMsgHead() PROTOBUF_FINAL;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR XMsgHead(
      ::google::protobuf::internal::ConstantInitialized);

  inline XMsgHead(const XMsgHead& from) : XMsgHead(nullptr, from) {}
  inline XMsgHead(XMsgHead&& from) noexcept
      : XMsgHead(nullptr, std::move(from)) {}
  inline XMsgHead& operator=(const XMsgHead& from) {
    CopyFrom(from);
    return *this;
  }
  inline XMsgHead& operator=(XMsgHead&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const XMsgHead& default_instance() {
    return *internal_default_instance();
  }
  static inline const XMsgHead* internal_default_instance() {
    return reinterpret_cast<const XMsgHead*>(
        &_XMsgHead_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(XMsgHead& a, XMsgHead& b) { a.Swap(&b); }
  inline void Swap(XMsgHead* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(XMsgHead* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  XMsgHead* New(::google::protobuf::Arena* arena = nullptr) const PROTOBUF_FINAL {
    return ::google::protobuf::Message::DefaultConstruct<XMsgHead>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const XMsgHead& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const XMsgHead& from) { XMsgHead::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(XMsgHead* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "XMsg.XMsgHead"; }

 protected:
  explicit XMsgHead(::google::protobuf::Arena* arena);
  XMsgHead(::google::protobuf::Arena* arena, const XMsgHead& from);
  XMsgHead(::google::protobuf::Arena* arena, XMsgHead&& from) noexcept
      : XMsgHead(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const PROTOBUF_FINAL;
  static const ::google::protobuf::Message::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kMsgStrFieldNumber = 2,
    kMsgSizeFieldNumber = 1,
  };
  // string msgStr = 2;
  void clear_msgstr() ;
  const std::string& msgstr() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_msgstr(Arg_&& arg, Args_... args);
  std::string* mutable_msgstr();
  PROTOBUF_NODISCARD std::string* release_msgstr();
  void set_allocated_msgstr(std::string* value);

  private:
  const std::string& _internal_msgstr() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msgstr(
      const std::string& value);
  std::string* _internal_mutable_msgstr();

  public:
  // int32 msgSize = 1;
  void clear_msgsize() ;
  ::int32_t msgsize() const;
  void set_msgsize(::int32_t value);

  private:
  ::int32_t _internal_msgsize() const;
  void _internal_set_msgsize(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:XMsg.XMsgHead)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      28, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_XMsgHead_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const XMsgHead& from_msg);
    ::google::protobuf::internal::ArenaStringPtr msgstr_;
    ::int32_t msgsize_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_XMsgHead_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// XMsgHead

// int32 msgSize = 1;
inline void XMsgHead::clear_msgsize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgsize_ = 0;
}
inline ::int32_t XMsgHead::msgsize() const {
  // @@protoc_insertion_point(field_get:XMsg.XMsgHead.msgSize)
  return _internal_msgsize();
}
inline void XMsgHead::set_msgsize(::int32_t value) {
  _internal_set_msgsize(value);
  // @@protoc_insertion_point(field_set:XMsg.XMsgHead.msgSize)
}
inline ::int32_t XMsgHead::_internal_msgsize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msgsize_;
}
inline void XMsgHead::_internal_set_msgsize(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgsize_ = value;
}

// string msgStr = 2;
inline void XMsgHead::clear_msgstr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgstr_.ClearToEmpty();
}
inline const std::string& XMsgHead::msgstr() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:XMsg.XMsgHead.msgStr)
  return _internal_msgstr();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void XMsgHead::set_msgstr(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgstr_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:XMsg.XMsgHead.msgStr)
}
inline std::string* XMsgHead::mutable_msgstr() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_msgstr();
  // @@protoc_insertion_point(field_mutable:XMsg.XMsgHead.msgStr)
  return _s;
}
inline const std::string& XMsgHead::_internal_msgstr() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.msgstr_.Get();
}
inline void XMsgHead::_internal_set_msgstr(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgstr_.Set(value, GetArena());
}
inline std::string* XMsgHead::_internal_mutable_msgstr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.msgstr_.Mutable( GetArena());
}
inline std::string* XMsgHead::release_msgstr() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:XMsg.XMsgHead.msgStr)
  return _impl_.msgstr_.Release();
}
inline void XMsgHead::set_allocated_msgstr(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.msgstr_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.msgstr_.IsDefault()) {
          _impl_.msgstr_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:XMsg.XMsgHead.msgStr)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace XMsg


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_XMsgHead_2eproto_2epb_2eh
