// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: XMsgCom.proto
// Protobuf C++ Version: 5.28.3

#include "XMsgCom.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace XMsg {

inline constexpr XMsgHead::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        servername_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgsize_{0},
        msgtype_{static_cast< ::XMsg::MsgType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XMsgHead::XMsgHead(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct XMsgHeadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XMsgHeadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XMsgHeadDefaultTypeInternal() {}
  union {
    XMsgHead _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XMsgHeadDefaultTypeInternal _XMsgHead_default_instance_;

inline constexpr XLoginRes::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        restype_{static_cast< ::XMsg::XLoginRes_XLoginResType >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XLoginRes::XLoginRes(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct XLoginResDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XLoginResDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XLoginResDefaultTypeInternal() {}
  union {
    XLoginRes _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XLoginResDefaultTypeInternal _XLoginRes_default_instance_;

inline constexpr XLoginReq::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        password_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XLoginReq::XLoginReq(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct XLoginReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XLoginReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XLoginReqDefaultTypeInternal() {}
  union {
    XLoginReq _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XLoginReqDefaultTypeInternal _XLoginReq_default_instance_;
}  // namespace XMsg
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_XMsgCom_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_XMsgCom_2eproto = nullptr;
const ::uint32_t
    TableStruct_XMsgCom_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.msgsize_),
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.msgtype_),
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.servername_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::XMsg::XLoginReq, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::XMsg::XLoginReq, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::XMsg::XLoginReq, _impl_.password_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::XMsg::XLoginRes, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::XMsg::XLoginRes, _impl_.restype_),
        PROTOBUF_FIELD_OFFSET(::XMsg::XLoginRes, _impl_.token_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::XMsg::XMsgHead)},
        {12, -1, -1, sizeof(::XMsg::XLoginReq)},
        {22, -1, -1, sizeof(::XMsg::XLoginRes)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::XMsg::_XMsgHead_default_instance_._instance,
    &::XMsg::_XLoginReq_default_instance_._instance,
    &::XMsg::_XLoginRes_default_instance_._instance,
};
const char descriptor_table_protodef_XMsgCom_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\rXMsgCom.proto\022\004XMsg\032\016XMsgType.proto\"^\n"
    "\010XMsgHead\022\017\n\007msgSize\030\001 \001(\005\022\036\n\007msgType\030\002 "
    "\001(\0162\r.XMsg.MsgType\022\r\n\005token\030\003 \001(\t\022\022\n\nser"
    "verName\030\004 \001(\t\"/\n\tXLoginReq\022\020\n\010username\030\001"
    " \001(\t\022\020\n\010password\030\002 \001(\t\"\205\001\n\tXLoginRes\022.\n\007"
    "resType\030\001 \001(\0162\035.XMsg.XLoginRes.XLoginRes"
    "Type\022\r\n\005token\030\002 \001(\t\"9\n\rXLoginResType\022\n\n\006"
    "XRT_OK\020\000\022\013\n\007XRT_ERR\020\001\022\017\n\013XRT_NO_USER\020\002b\006"
    "proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_XMsgCom_2eproto_deps[1] =
    {
        &::descriptor_table_XMsgType_2eproto,
};
static ::absl::once_flag descriptor_table_XMsgCom_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_XMsgCom_2eproto = {
    false,
    false,
    326,
    descriptor_table_protodef_XMsgCom_2eproto,
    "XMsgCom.proto",
    &descriptor_table_XMsgCom_2eproto_once,
    descriptor_table_XMsgCom_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_XMsgCom_2eproto::offsets,
    file_level_enum_descriptors_XMsgCom_2eproto,
    file_level_service_descriptors_XMsgCom_2eproto,
};
namespace XMsg {
const ::google::protobuf::EnumDescriptor* XLoginRes_XLoginResType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_XMsgCom_2eproto);
  return file_level_enum_descriptors_XMsgCom_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t XLoginRes_XLoginResType_internal_data_[] = {
    196608u, 0u, };
bool XLoginRes_XLoginResType_IsValid(int value) {
  return 0 <= value && value <= 2;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr XLoginRes_XLoginResType XLoginRes::XRT_OK;
constexpr XLoginRes_XLoginResType XLoginRes::XRT_ERR;
constexpr XLoginRes_XLoginResType XLoginRes::XRT_NO_USER;
constexpr XLoginRes_XLoginResType XLoginRes::XLoginResType_MIN;
constexpr XLoginRes_XLoginResType XLoginRes::XLoginResType_MAX;
constexpr int XLoginRes::XLoginResType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class XMsgHead::_Internal {
 public:
};

XMsgHead::XMsgHead(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:XMsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::XMsg::XMsgHead& from_msg)
      : token_(arena, from.token_),
        servername_(arena, from.servername_),
        _cached_size_{0} {}

XMsgHead::XMsgHead(
    ::google::protobuf::Arena* arena,
    const XMsgHead& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  XMsgHead* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msgsize_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, msgsize_),
           offsetof(Impl_, msgtype_) -
               offsetof(Impl_, msgsize_) +
               sizeof(Impl_::msgtype_));

  // @@protoc_insertion_point(copy_constructor:XMsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        servername_(arena),
        _cached_size_{0} {}

inline void XMsgHead::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, msgsize_),
           0,
           offsetof(Impl_, msgtype_) -
               offsetof(Impl_, msgsize_) +
               sizeof(Impl_::msgtype_));
}
XMsgHead::~XMsgHead() {
  // @@protoc_insertion_point(destructor:XMsg.XMsgHead)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XMsgHead::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.servername_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    XMsgHead::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_XMsgHead_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &XMsgHead::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<XMsgHead>(),
            ::google::protobuf::Message::GetNewImpl<XMsgHead>(),
            ::google::protobuf::Message::GetClearImpl<XMsgHead>(), &XMsgHead::ByteSizeLong,
                &XMsgHead::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_._cached_size_),
            false,
        },
        &XMsgHead::kDescriptorMethods,
        &descriptor_table_XMsgCom_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* XMsgHead::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 37, 2> XMsgHead::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::XMsg::XMsgHead>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string serverName = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.servername_)}},
    // int32 msgSize = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XMsgHead, _impl_.msgsize_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_)}},
    // .XMsg.MsgType msgType = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XMsgHead, _impl_.msgtype_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgtype_)}},
    // string token = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.token_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 msgSize = 1;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .XMsg.MsgType msgType = 2;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgtype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string token = 3;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string serverName = 4;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.servername_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\0\5\12\0\0\0"
    "XMsg.XMsgHead"
    "token"
    "serverName"
  }},
};

PROTOBUF_NOINLINE void XMsgHead::Clear() {
// @@protoc_insertion_point(message_clear_start:XMsg.XMsgHead)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.servername_.ClearToEmpty();
  ::memset(&_impl_.msgsize_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.msgtype_) -
      reinterpret_cast<char*>(&_impl_.msgsize_)) + sizeof(_impl_.msgtype_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* XMsgHead::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const XMsgHead& this_ = static_cast<const XMsgHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* XMsgHead::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const XMsgHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:XMsg.XMsgHead)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 msgSize = 1;
          if (this_._internal_msgsize() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_msgsize(), target);
          }

          // .XMsg.MsgType msgType = 2;
          if (this_._internal_msgtype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_msgtype(), target);
          }

          // string token = 3;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "XMsg.XMsgHead.token");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          // string serverName = 4;
          if (!this_._internal_servername().empty()) {
            const std::string& _s = this_._internal_servername();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "XMsg.XMsgHead.serverName");
            target = stream->WriteStringMaybeAliased(4, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:XMsg.XMsgHead)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t XMsgHead::ByteSizeLong(const MessageLite& base) {
          const XMsgHead& this_ = static_cast<const XMsgHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t XMsgHead::ByteSizeLong() const {
          const XMsgHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:XMsg.XMsgHead)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string token = 3;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // string serverName = 4;
            if (!this_._internal_servername().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_servername());
            }
            // int32 msgSize = 1;
            if (this_._internal_msgsize() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_msgsize());
            }
            // .XMsg.MsgType msgType = 2;
            if (this_._internal_msgtype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_msgtype());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void XMsgHead::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<XMsgHead*>(&to_msg);
  auto& from = static_cast<const XMsgHead&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:XMsg.XMsgHead)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (!from._internal_servername().empty()) {
    _this->_internal_set_servername(from._internal_servername());
  }
  if (from._internal_msgsize() != 0) {
    _this->_impl_.msgsize_ = from._impl_.msgsize_;
  }
  if (from._internal_msgtype() != 0) {
    _this->_impl_.msgtype_ = from._impl_.msgtype_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XMsgHead::CopyFrom(const XMsgHead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XMsg.XMsgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void XMsgHead::InternalSwap(XMsgHead* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.servername_, &other->_impl_.servername_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgtype_)
      + sizeof(XMsgHead::_impl_.msgtype_)
      - PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_)>(
          reinterpret_cast<char*>(&_impl_.msgsize_),
          reinterpret_cast<char*>(&other->_impl_.msgsize_));
}

::google::protobuf::Metadata XMsgHead::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class XLoginReq::_Internal {
 public:
};

XLoginReq::XLoginReq(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:XMsg.XLoginReq)
}
inline PROTOBUF_NDEBUG_INLINE XLoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::XMsg::XLoginReq& from_msg)
      : username_(arena, from.username_),
        password_(arena, from.password_),
        _cached_size_{0} {}

XLoginReq::XLoginReq(
    ::google::protobuf::Arena* arena,
    const XLoginReq& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  XLoginReq* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:XMsg.XLoginReq)
}
inline PROTOBUF_NDEBUG_INLINE XLoginReq::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : username_(arena),
        password_(arena),
        _cached_size_{0} {}

inline void XLoginReq::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
XLoginReq::~XLoginReq() {
  // @@protoc_insertion_point(destructor:XMsg.XLoginReq)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XLoginReq::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.username_.Destroy();
  _impl_.password_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    XLoginReq::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_XLoginReq_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &XLoginReq::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<XLoginReq>(),
            ::google::protobuf::Message::GetNewImpl<XLoginReq>(),
            ::google::protobuf::Message::GetClearImpl<XLoginReq>(), &XLoginReq::ByteSizeLong,
                &XLoginReq::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_._cached_size_),
            false,
        },
        &XLoginReq::kDescriptorMethods,
        &descriptor_table_XMsgCom_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* XLoginReq::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 39, 2> XLoginReq::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::XMsg::XLoginReq>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string password = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.password_)}},
    // string username = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.username_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string username = 1;
    {PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string password = 2;
    {PROTOBUF_FIELD_OFFSET(XLoginReq, _impl_.password_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\10\10\0\0\0\0\0"
    "XMsg.XLoginReq"
    "username"
    "password"
  }},
};

PROTOBUF_NOINLINE void XLoginReq::Clear() {
// @@protoc_insertion_point(message_clear_start:XMsg.XLoginReq)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  _impl_.password_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* XLoginReq::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const XLoginReq& this_ = static_cast<const XLoginReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* XLoginReq::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const XLoginReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:XMsg.XLoginReq)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string username = 1;
          if (!this_._internal_username().empty()) {
            const std::string& _s = this_._internal_username();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "XMsg.XLoginReq.username");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string password = 2;
          if (!this_._internal_password().empty()) {
            const std::string& _s = this_._internal_password();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "XMsg.XLoginReq.password");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:XMsg.XLoginReq)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t XLoginReq::ByteSizeLong(const MessageLite& base) {
          const XLoginReq& this_ = static_cast<const XLoginReq&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t XLoginReq::ByteSizeLong() const {
          const XLoginReq& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:XMsg.XLoginReq)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string username = 1;
            if (!this_._internal_username().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_username());
            }
            // string password = 2;
            if (!this_._internal_password().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_password());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void XLoginReq::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<XLoginReq*>(&to_msg);
  auto& from = static_cast<const XLoginReq&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:XMsg.XLoginReq)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  if (!from._internal_password().empty()) {
    _this->_internal_set_password(from._internal_password());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XLoginReq::CopyFrom(const XLoginReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XMsg.XLoginReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void XLoginReq::InternalSwap(XLoginReq* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
}

::google::protobuf::Metadata XLoginReq::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class XLoginRes::_Internal {
 public:
};

XLoginRes::XLoginRes(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:XMsg.XLoginRes)
}
inline PROTOBUF_NDEBUG_INLINE XLoginRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::XMsg::XLoginRes& from_msg)
      : token_(arena, from.token_),
        _cached_size_{0} {}

XLoginRes::XLoginRes(
    ::google::protobuf::Arena* arena,
    const XLoginRes& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  XLoginRes* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.restype_ = from._impl_.restype_;

  // @@protoc_insertion_point(copy_constructor:XMsg.XLoginRes)
}
inline PROTOBUF_NDEBUG_INLINE XLoginRes::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : token_(arena),
        _cached_size_{0} {}

inline void XLoginRes::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.restype_ = {};
}
XLoginRes::~XLoginRes() {
  // @@protoc_insertion_point(destructor:XMsg.XLoginRes)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XLoginRes::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.token_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    XLoginRes::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_XLoginRes_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &XLoginRes::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<XLoginRes>(),
            ::google::protobuf::Message::GetNewImpl<XLoginRes>(),
            ::google::protobuf::Message::GetClearImpl<XLoginRes>(), &XLoginRes::ByteSizeLong,
                &XLoginRes::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_._cached_size_),
            false,
        },
        &XLoginRes::kDescriptorMethods,
        &descriptor_table_XMsgCom_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* XLoginRes::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 28, 2> XLoginRes::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::XMsg::XLoginRes>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.token_)}},
    // .XMsg.XLoginRes.XLoginResType resType = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XLoginRes, _impl_.restype_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.restype_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .XMsg.XLoginRes.XLoginResType resType = 1;
    {PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.restype_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string token = 2;
    {PROTOBUF_FIELD_OFFSET(XLoginRes, _impl_.token_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\16\0\5\0\0\0\0\0"
    "XMsg.XLoginRes"
    "token"
  }},
};

PROTOBUF_NOINLINE void XLoginRes::Clear() {
// @@protoc_insertion_point(message_clear_start:XMsg.XLoginRes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.token_.ClearToEmpty();
  _impl_.restype_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* XLoginRes::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const XLoginRes& this_ = static_cast<const XLoginRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* XLoginRes::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const XLoginRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:XMsg.XLoginRes)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // .XMsg.XLoginRes.XLoginResType resType = 1;
          if (this_._internal_restype() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                1, this_._internal_restype(), target);
          }

          // string token = 2;
          if (!this_._internal_token().empty()) {
            const std::string& _s = this_._internal_token();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "XMsg.XLoginRes.token");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:XMsg.XLoginRes)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t XLoginRes::ByteSizeLong(const MessageLite& base) {
          const XLoginRes& this_ = static_cast<const XLoginRes&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t XLoginRes::ByteSizeLong() const {
          const XLoginRes& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:XMsg.XLoginRes)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string token = 2;
            if (!this_._internal_token().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_token());
            }
            // .XMsg.XLoginRes.XLoginResType resType = 1;
            if (this_._internal_restype() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_restype());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void XLoginRes::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<XLoginRes*>(&to_msg);
  auto& from = static_cast<const XLoginRes&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:XMsg.XLoginRes)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_token().empty()) {
    _this->_internal_set_token(from._internal_token());
  }
  if (from._internal_restype() != 0) {
    _this->_impl_.restype_ = from._impl_.restype_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XLoginRes::CopyFrom(const XLoginRes& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XMsg.XLoginRes)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void XLoginRes::InternalSwap(XLoginRes* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  swap(_impl_.restype_, other->_impl_.restype_);
}

::google::protobuf::Metadata XLoginRes::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace XMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_XMsgCom_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
