// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: XMsgHead.proto
// Protobuf C++ Version: 5.28.3

#include "XMsgHead.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace XMsg {

inline constexpr XMsgHead::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msgstr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgsize_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XMsgHead::XMsgHead(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct XMsgHeadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XMsgHeadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XMsgHeadDefaultTypeInternal() {}
  union {
    XMsgHead _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XMsgHeadDefaultTypeInternal _XMsgHead_default_instance_;
}  // namespace XMsg
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_XMsgHead_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_XMsgHead_2eproto = nullptr;
const ::uint32_t
    TableStruct_XMsgHead_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.msgsize_),
        PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.msgstr_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::XMsg::XMsgHead)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::XMsg::_XMsgHead_default_instance_._instance,
};
const char descriptor_table_protodef_XMsgHead_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016XMsgHead.proto\022\004XMsg\"+\n\010XMsgHead\022\017\n\007ms"
    "gSize\030\001 \001(\005\022\016\n\006msgStr\030\002 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_XMsgHead_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_XMsgHead_2eproto = {
    false,
    false,
    75,
    descriptor_table_protodef_XMsgHead_2eproto,
    "XMsgHead.proto",
    &descriptor_table_XMsgHead_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_XMsgHead_2eproto::offsets,
    file_level_enum_descriptors_XMsgHead_2eproto,
    file_level_service_descriptors_XMsgHead_2eproto,
};
namespace XMsg {
// ===================================================================

class XMsgHead::_Internal {
 public:
};

XMsgHead::XMsgHead(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:XMsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::XMsg::XMsgHead& from_msg)
      : msgstr_(arena, from.msgstr_),
        _cached_size_{0} {}

XMsgHead::XMsgHead(
    ::google::protobuf::Arena* arena,
    const XMsgHead& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  XMsgHead* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.msgsize_ = from._impl_.msgsize_;

  // @@protoc_insertion_point(copy_constructor:XMsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msgstr_(arena),
        _cached_size_{0} {}

inline void XMsgHead::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.msgsize_ = {};
}
XMsgHead::~XMsgHead() {
  // @@protoc_insertion_point(destructor:XMsg.XMsgHead)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XMsgHead::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msgstr_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    XMsgHead::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_XMsgHead_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &XMsgHead::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<XMsgHead>(),
            ::google::protobuf::Message::GetNewImpl<XMsgHead>(),
            ::google::protobuf::Message::GetClearImpl<XMsgHead>(), &XMsgHead::ByteSizeLong,
                &XMsgHead::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_._cached_size_),
            false,
        },
        &XMsgHead::kDescriptorMethods,
        &descriptor_table_XMsgHead_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* XMsgHead::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 28, 2> XMsgHead::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::XMsg::XMsgHead>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string msgStr = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgstr_)}},
    // int32 msgSize = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XMsgHead, _impl_.msgsize_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 msgSize = 1;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string msgStr = 2;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgstr_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\6\0\0\0\0\0"
    "XMsg.XMsgHead"
    "msgStr"
  }},
};

PROTOBUF_NOINLINE void XMsgHead::Clear() {
// @@protoc_insertion_point(message_clear_start:XMsg.XMsgHead)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msgstr_.ClearToEmpty();
  _impl_.msgsize_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* XMsgHead::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const XMsgHead& this_ = static_cast<const XMsgHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* XMsgHead::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const XMsgHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:XMsg.XMsgHead)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 msgSize = 1;
          if (this_._internal_msgsize() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_msgsize(), target);
          }

          // string msgStr = 2;
          if (!this_._internal_msgstr().empty()) {
            const std::string& _s = this_._internal_msgstr();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "XMsg.XMsgHead.msgStr");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:XMsg.XMsgHead)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t XMsgHead::ByteSizeLong(const MessageLite& base) {
          const XMsgHead& this_ = static_cast<const XMsgHead&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t XMsgHead::ByteSizeLong() const {
          const XMsgHead& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:XMsg.XMsgHead)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string msgStr = 2;
            if (!this_._internal_msgstr().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_msgstr());
            }
            // int32 msgSize = 1;
            if (this_._internal_msgsize() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_msgsize());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void XMsgHead::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<XMsgHead*>(&to_msg);
  auto& from = static_cast<const XMsgHead&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:XMsg.XMsgHead)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msgstr().empty()) {
    _this->_internal_set_msgstr(from._internal_msgstr());
  }
  if (from._internal_msgsize() != 0) {
    _this->_impl_.msgsize_ = from._impl_.msgsize_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XMsgHead::CopyFrom(const XMsgHead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XMsg.XMsgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void XMsgHead::InternalSwap(XMsgHead* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msgstr_, &other->_impl_.msgstr_, arena);
        swap(_impl_.msgsize_, other->_impl_.msgsize_);
}

::google::protobuf::Metadata XMsgHead::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace XMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_XMsgHead_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
