// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: XMsgHead.proto

#include "XMsgHead.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace XMsg {

inline constexpr XMsgHead::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : msgstr_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        msgsize_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR XMsgHead::XMsgHead(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct XMsgHeadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR XMsgHeadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~XMsgHeadDefaultTypeInternal() {}
  union {
    XMsgHead _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 XMsgHeadDefaultTypeInternal _XMsgHead_default_instance_;
}  // namespace XMsg
static ::_pb::Metadata file_level_metadata_XMsgHead_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_XMsgHead_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_XMsgHead_2eproto = nullptr;
const ::uint32_t TableStruct_XMsgHead_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.msgsize_),
    PROTOBUF_FIELD_OFFSET(::XMsg::XMsgHead, _impl_.msgstr_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::XMsg::XMsgHead)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::XMsg::_XMsgHead_default_instance_._instance,
};
const char descriptor_table_protodef_XMsgHead_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\016XMsgHead.proto\022\004XMsg\"+\n\010XMsgHead\022\017\n\007ms"
    "gSize\030\001 \001(\005\022\016\n\006msgStr\030\002 \001(\tb\006proto3"
};
static ::absl::once_flag descriptor_table_XMsgHead_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_XMsgHead_2eproto = {
    false,
    false,
    75,
    descriptor_table_protodef_XMsgHead_2eproto,
    "XMsgHead.proto",
    &descriptor_table_XMsgHead_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_XMsgHead_2eproto::offsets,
    file_level_metadata_XMsgHead_2eproto,
    file_level_enum_descriptors_XMsgHead_2eproto,
    file_level_service_descriptors_XMsgHead_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_XMsgHead_2eproto_getter() {
  return &descriptor_table_XMsgHead_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_XMsgHead_2eproto(&descriptor_table_XMsgHead_2eproto);
namespace XMsg {
// ===================================================================

class XMsgHead::_Internal {
 public:
};

XMsgHead::XMsgHead(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:XMsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : msgstr_(arena, from.msgstr_),
        _cached_size_{0} {}

XMsgHead::XMsgHead(
    ::google::protobuf::Arena* arena,
    const XMsgHead& from)
    : ::google::protobuf::Message(arena) {
  XMsgHead* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.msgsize_ = from._impl_.msgsize_;

  // @@protoc_insertion_point(copy_constructor:XMsg.XMsgHead)
}
inline PROTOBUF_NDEBUG_INLINE XMsgHead::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : msgstr_(arena),
        _cached_size_{0} {}

inline void XMsgHead::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.msgsize_ = {};
}
XMsgHead::~XMsgHead() {
  // @@protoc_insertion_point(destructor:XMsg.XMsgHead)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void XMsgHead::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.msgstr_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void XMsgHead::Clear() {
// @@protoc_insertion_point(message_clear_start:XMsg.XMsgHead)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.msgstr_.ClearToEmpty();
  _impl_.msgsize_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* XMsgHead::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 28, 2> XMsgHead::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_XMsgHead_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string msgStr = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgstr_)}},
    // int32 msgSize = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(XMsgHead, _impl_.msgsize_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 msgSize = 1;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgsize_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // string msgStr = 2;
    {PROTOBUF_FIELD_OFFSET(XMsgHead, _impl_.msgstr_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\15\0\6\0\0\0\0\0"
    "XMsg.XMsgHead"
    "msgStr"
  }},
};

::uint8_t* XMsgHead::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:XMsg.XMsgHead)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 msgSize = 1;
  if (this->_internal_msgsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_msgsize(), target);
  }

  // string msgStr = 2;
  if (!this->_internal_msgstr().empty()) {
    const std::string& _s = this->_internal_msgstr();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "XMsg.XMsgHead.msgStr");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:XMsg.XMsgHead)
  return target;
}

::size_t XMsgHead::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:XMsg.XMsgHead)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string msgStr = 2;
  if (!this->_internal_msgstr().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_msgstr());
  }

  // int32 msgSize = 1;
  if (this->_internal_msgsize() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_msgsize());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData XMsgHead::_class_data_ = {
    XMsgHead::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* XMsgHead::GetClassData() const {
  return &_class_data_;
}

void XMsgHead::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<XMsgHead*>(&to_msg);
  auto& from = static_cast<const XMsgHead&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:XMsg.XMsgHead)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_msgstr().empty()) {
    _this->_internal_set_msgstr(from._internal_msgstr());
  }
  if (from._internal_msgsize() != 0) {
    _this->_internal_set_msgsize(from._internal_msgsize());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void XMsgHead::CopyFrom(const XMsgHead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:XMsg.XMsgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool XMsgHead::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* XMsgHead::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void XMsgHead::InternalSwap(XMsgHead* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.msgstr_, &other->_impl_.msgstr_, arena);
        swap(_impl_.msgsize_, other->_impl_.msgsize_);
}

::google::protobuf::Metadata XMsgHead::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_XMsgHead_2eproto_getter, &descriptor_table_XMsgHead_2eproto_once,
      file_level_metadata_XMsgHead_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace XMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
